sudo: required
services:
  - docker

before_install:
  - docker build -t johnpoff/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true johnpoff/react-test npm test 
  # -- --coverage

after_success:
  - docker build -t johnpoff/multi-client ./client 
  - docker build -t johnpoff/multi-nginx ./nginx
  - docker build -t johnpoff/multi-server ./server
  - docker built -t johnpoff/multi-worker ./worker
# Log in to the Docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take these images and push to Docker hub
- docker push johnpoff/multi-client
- docker push johnpoff/multi-nginx
- docker push johnpoff/multi-server
- docker push johnpoff/multi-worker


